var place = {
    " Minn.": "Minnesota",
    "A.L.": "Alabama",
    "A.R.": "Arizona",
    "Ala.": "Alabama",
    "Ala.]": "Alabama",
    "Ariz.": "Arizona",
    "Ark.": "Arkansas",
    "Ark.]": "Arkansas",
    "Avery Co.": "Avery County",
    "B.C.": "British Columbia",
    "Baltimore Co.": "Baltimore County",
    "Belgium]": "Belgium",
    "Burlington Co.": "Burlington County",
    "C. A.": "California",
    "C.A.": "California",
    "C.O.": "Colorado",
    "C.T.": "Connecticut",
    "CA": "California",
    "CA,": "California",
    "CA.": "California",
    "CA]": "California",
    "CT.": "Connecticut",
    "Ca.": "California",
    "Cal.": "California",
    "Calif": "California",
    "Calif.": "California",
    "Calif. ;": "California",
    "Calif.:": "California",
    "Calif.]": "California",
    "California?]": "California",
    "California]": "California",
    "Callifornia": "California",
    "Co.": "County",
    "Coahoma Co.": "Coahoma County",
    "Col.": "Colorado",
    "Colo.": "Colorado",
    "Colo.]": "Colorado",
    "Columbiana Co.": "Columbiana County",
    "Conn.": "Connecticut",
    "Conn. ;": "Connecticut",
    "Conn.]": "Connecticut",
    "D.C": "D.C.",
    "D.C. ;": "D.C.",
    "D.E.": "Delaware",
    "Del.": "Delaware",
    "Deleware": "Delaware",
    "Door Co.": "Door County",
    "Dupage Co.": "Dupage County",
    "F.L": "Florida",
    "F.L.": "Florida",
    "F.L..": "Florida",
    "F.L.]": "Florida",
    "FL": "Florida",
    "Fl.": "Florida",
    "Fla.": "Florida",
    "Fla. ;": "Florida",
    "Fla.]": "Florida",
    "Florida ;": "Florida",
    "Florida.": "Florida",
    "Fresno Co.": "Fresno County",
    "G.A.": "Georgia",
    "GA.": "Georgia",
    "Ga": "Georgia",
    "Ga.": "Georgia",
    "Ga. ;": "Georgia",
    "Ga.]": "Georgia",
    "Geauga Co.": "Geauga County",
    "Georgia.": "Georgia",
    "Georgia]": "Georgia",
    "Holland ;": "Holland",
    "I.A.": "Iowa",
    "I.D.": "Idaho",
    "I.L.": "Illinois",
    "I.N.": "Indiana",
    "IA": "Iowa",
    "IL": "Illinois",
    "Ia.": "Iowa",
    "Ill": "Illinois",
    "Ill.": "Illinois",
    "Ill. ;": "Illinois",
    "Ill.,": "Illinois",
    "Ill.:": "Illinois",
    "Ill.]": "Illinois",
    "[Illinois": ", Illinois",
    "[Illinois]": ", Illinois",
    "Chicago.": "Chicago,",
    "Illinois ;": "Illinois",
    "Ind.": "Indiana",
    "Iowa .": "Iowa",
    "Iowa]": "Iowa",
    "K. S.": "Kansas",
    "K.S.": "Kansas",
    "K.Y.": "Kentucky",
    "Kan": "Kansas",
    "Kan.": "Kansas",
    "Kan. ;": "Kansas",
    "Kan.]": "Kansas",
    "Kans. ;": "Kansas",
    "Kansas ;": "Kansas",
    "Kas.": "Kansas",
    "Ky": "Kentucky",
    "Ky.": "Kentucky",
    "L.A.": "Louisiana",
    "L.I.": "Long Island",
    "L.I. [New York]": "Long Island",
    "La.": "Louisiana",
    "Lake Co.": "Lake County",
    "Lanc. Co.": "Lancaster County",
    "Lancaster Co.": "Lancaster County",
    "Livingston Co.": "Livingston County",
    "Long island": "Long Island",
    "M. A.": "Massachusetts",
    "M.A.": "Massachusetts",
    "M.A..": "Massachusetts",
    "M.A.:": "Massachusetts",
    "M.D.": "Maryland",
    "M.E.": "Maine",
    "M.I.": "Michigan",
    "M.O.": "Missouri",
    "M.S.": "Mississippi",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Mississippi",
    "MO.": "Missouri",
    "Maryland ;": "Maryland",
    "Mass": "Massachusetts",
    "Mass.": "Massachusetts",
    "Mass. :": "Massachusetts",
    "Mass. ;": "Massachusetts",
    "Mass.,": "Massachusetts",
    "Mass.:": "Massachusetts",
    "Mass.]": "Massachusetts",
    "Massachusetts ;": "Massachusetts",
    "McDowell Co.": "McDowell County",
    "McHenry Co.": "McHenry County",
    "McLean Co.": "McLean County",
    "Md.": "Maryland",
    "Md. ;": "Maryland",
    "Me.": "Maine",
    "Mendocino Co.": "Mendocino County",
    "Miami Co.": "Miami County",
    "Mich": "Michigan",
    "Mich.": "Michigan",
    "Mich. ;": "Michigan",
    "Mich.]": "Michigan",
    "Mifflin Co.": "Mifflin County",
    "Minn": "Minnesota",
    "Minn.": "Minnesota",
    "Minn. ;": "Minnesota",
    "Minnesota]": "Minnesota",
    "Miss.": "Mississippi",
    "Miss. ;": "Mississippi",
    "Mo.": "Missouri",
    "Mo. ;": "Missouri",
    "Mo.]": "Missouri",
    "Monmouth Co.": "Monmouth County",
    "Mont.": "Montana",
    "Montgomery Co.": "Montgomery County",
    "N. Dak.": "North Dakota",
    "N. H.": "New Hampshire",
    "N. J.": "New Jersey",
    "N. Y.": "New York",
    "N.B.": "unknown",
    "N.C.": "North Carolina",
    "N.C. :": "North Carolina",
    "N.C.]": "North Carolina",
    "N.D.": "North Dakota",
    "N.E.": "Nebraska",
    "N.H.": "New Hampshire",
    "N.J": "New Jersey",
    "N.J.": "New Jersey",
    "N.J. (formerly Edgewater": "New Jersey",
    "N.J. William Tricker & Co.,": "New Jersey",
    "N.J.:": "New Jersey",
    "N.J.]": "New Jersey",
    "N.M.": "New Mexico",
    "N.S.": "Nova Scotia",
    "N.Y": "New York",
    "N.Y.": "New York",
    "N.Y. .": "New York",
    "N.Y. ;": "New York",
    "N.Y. Batavia Nurseries ;": "New York",
    "N.Y..": "New York",
    "N.Y.:": "New York",
    "N.Y.]": "New York",
    "NJ": "New Jersey",
    "NJ.": "New Jersey",
    "NY": "New York",
    "NY.": "New York",
    "Neb.": "Nebraska",
    "Neb.]": "Nebraska",
    "Nebr.": "Nebraska",
    "New Jersey ;": "New Jersey",
    "New York City": "New York",
    "New York State": "New York",
    "O.": "Ohio",
    "O.,": "Ohio",
    "O.H.": "Ohio",
    "O.H.]": "Ohio",
    "O.R.": "Oregon",
    "OH": "Ohio",
    "Oh.": "Ohio",
    "Ohio ;": "Ohio",
    "Ohio.": "Ohio",
    "Ohio]": "Ohio",
    "Okla.": "Oklahoma",
    "Okla.]": "Oklahoma",
    "Ont.": "Ontario",
    "Ontario Co.": "Ontario County",
    "Or.": "Oregon",
    "Or.]": "Oregon",
    "Ore.": "Oregon",
    "Oregon": "Oregon",
    "Oregon]": "Oregon",
    "Oswego Co.": "Oswego County",
    "P.A.": "Pennsylvania",
    "P.A..": "Pennsylvania",
    "P.A.]": "Pennsylvania",
    "P.O.": "Post Office",
    "PA": "Pennsylvania",
    "PA.": "Pennsylvania",
    "PA]": "Pennsylvania",
    "Pa": "Pennsylvania",
    "Pa.": "Pennsylvania",
    "Pa. ;": "Pennsylvania",
    "Pa.]": "Pennsylvania",
    "Page Co.": "Page County",
    "Penn'a.": "Pennsylvania",
    "Penn.": "Pennsylvania",
    "Penna": "Pennsylvania",
    "Penna.": "Pennsylvania",
    "Pennsylvania.": "Pennsylvania",
    "Pennsyvania": "Pennsylvania",
    "Pennsyvania.": "Pennsylvania",
    "Phila.": "Philadelphia",
    "Phildelphia [Pennsylvania] U.S.A.": "Philadelphia, Pennsylvania",
    "Portage Co.": "Portage County",
    "Queens": "Queens County",
    "Queens Co.": "Queens County",
    "R. I.": "Rhode Island",
    "R.I.": "Rhode Island",
    "S.C.": "South Carolina",
    "S.C. ;": "South Carolina",
    "S.D.": "South Dakota",
    "S.D.]": "South Dakota",
    "Santa Cruz Co.": "Santa Cruz County",
    "So. Dak.": "South Dakota",
    "So. Dakota": "South Dakota",
    "South Dakota]": "South Dakota",
    "Steuben Co.": "Steuben County",
    "T. N.": "Tennessee",
    "T.N": "Tennessee",
    "T.N.": "Tennessee",
    "T.X.": "Texas",
    "T.X..": "Texas",
    "TX": "Texas",
    "Tenn": "Tennessee",
    "Tenn.": "Tennessee",
    "Tennessee": "Tennessee",
    "Tex.": "Texas",
    "Tex. ;": "Texas",
    "Tex.]": "Texas",
    "Texas ;": "Texas",
    "Trumbull Co.": "Trumbull County",
    "Tx": "Texas",
    "Tx.": "Texas",
    "U.T.": "Utah",
    "Ut.": "Utah",
    "U.S.A.": "",
    "V. A.": "Virginia",
    "V.A.": "Virginia",
    "VT": "Vermont",
    "Va.": "Virginia",
    "Viginia": "Virginia",
    "Virginia:": "Virginia",
    "Vt.": "Vermont",
    "Vt.]": "Vermont",
    "W. I.": "Wisconsin",
    "W. Va.": "West Virginia",
    "W.A.": "Washington",
    "W.I.": "Wisconsin",
    "WI": "Wisconsin",
    "Wash": "Washington",
    "Wash.": "Washington",
    "Wash.]": "Washington",
    "Wis.": "Wisconsin",
    "Wis.]": "Wisconsin",
    "Wisc.": "Wisconsin",
    "[Berrien County]": "Berrien County",
    "[Boston]": "Boston",
    "[Dorchester County]": "Dorchester County",
    "[Ingham County]": "Ingham County",
    "[Kent County]": "Kent County",
    "[Manistee County]": "Manistee County",
    "[Marin County]": "Marin County",
    "[Miami County]": "Miami County",
    "[Montgomery County]": "Montgomery County",
    "[New York]": "New York",
    "[Plymouth County]": "Plymouth County",
    "[Pope County]": "Pope County",
    "[Womelsdorf]": "Womelsdorf",
};
module.exports.place = place
